swagger: "2.0"
info:
  title: BubberDinner.Api
  description: This Api provide create menu, book dinner, register functions.
  version: 1.0.0
host: localhost:5046
schemes:
  - https
paths:
  /auth/register:
    get:
      summary: "Provide user registration functionality"
      responses:
        "200":
          description: "OK"
  /auth/login:
    get:
      summary: "For user to log in"
      responses:
        "200":
          description: "OK"
  /Dinners:
    get:
      summary: "For user to view the dinner details"
      responses:
        "200":
          description: "OK"
  /host/{hostId}/menus:
    post:
      summary: "For user to create a menu"
      parameters:
        - name: "hostId"
          type: string
          required: true
          in: "path"
      responses:
        "200":
          description: "OK"
  /error:
    get:
      summary: "error end point to return error response"
      responses:
        "200":
          description: "OK"